#!/usr/bin/env bash

# Push the exact, already-reviewed main-branch commit after running the local
# release checks. This script intentionally does not create a commit: review
# and merge happen before deployment, so the SHA verified here is the SHA that
# CI and the hosting platform can identify.

set -Eeuo pipefail
IFS=$'\n\t'

readonly script_name="$(basename "$0")"
readonly repo_root="$(git rev-parse --show-toplevel 2>/dev/null || true)"

if [[ -z "$repo_root" ]]; then
  echo "${script_name}: run this script from inside the Git repository." >&2
  exit 64
fi

cd "$repo_root"

remote_name="${DEPLOY_REMOTE:-origin}"
deploy_branch="${DEPLOY_BRANCH:-main}"

current_branch="$(git symbolic-ref --quiet --short HEAD || true)"
if [[ "$current_branch" != "$deploy_branch" ]]; then
  echo "${script_name}: deployment must run from '$deploy_branch' (currently '${current_branch:-detached HEAD}')." >&2
  exit 65
fi

if [[ -n "$(git status --porcelain)" ]]; then
  echo "${script_name}: working tree is not clean; commit and review changes before deploying." >&2
  git status --short >&2
  exit 66
fi

if ! git remote get-url "$remote_name" >/dev/null 2>&1; then
  echo "${script_name}: Git remote '$remote_name' does not exist." >&2
  exit 67
fi

commit_sha="$(git rev-parse HEAD)"
echo "Running release checks for ${commit_sha}..."

# The manifest generated by Vite records this exact SHA in dist/deployment.json.
# CI supplies the same value through GITHUB_SHA; setting it here keeps local
# releases and CI releases equivalent.
YARDGUARD_COMMIT_SHA="$commit_sha" npm test
YARDGUARD_COMMIT_SHA="$commit_sha" npm run build
YARDGUARD_EXPECTED_COMMIT_SHA="$commit_sha" npm run test:dist

echo "Pushing ${commit_sha} to ${remote_name}/${deploy_branch}..."
git push "$remote_name" "HEAD:${deploy_branch}"

remote_sha="$(git ls-remote "$remote_name" "refs/heads/${deploy_branch}" | awk 'NR == 1 { print $1 }')"
if [[ "$remote_sha" != "$commit_sha" ]]; then
  echo "${script_name}: remote verification failed (expected ${commit_sha}, got ${remote_sha:-no ref})." >&2
  exit 68
fi

echo "Verified ${remote_name}/${deploy_branch} at ${commit_sha}."
echo "CI/hosting can now deploy this exact Git SHA."
